name: PluginCore
version: '${project.version}'
main: com.github.constmine.plugin.plugincore.PluginCore
api-version: 1.18
authors: [ ConstMine ]
description: It's for experiment.

commands:
  openInv:
    aliases:
      -inv
      -newInv
      -oI

  playerList:
